### ISSUE TITLE
H2EK Debug memory non-heap allocation tracking table overflow.

### ISSUE THREAD

**Issue by RubyofBlue** [Joint-Issue-Tracker/Joint-Issue-Tracker#118]
### Issue type: Is this a bug or feature request?

Bug

### Which game's editing kit is affected by the issue?

H2EK

### Which tools are affected by the issue?

- [ ] Guerilla (`guerilla.exe`)
- [ ] Foundation (`Foundation.exe`)
- [X] Sapien (`sapien.exe`)
- [X] Standalone (`halox_tag_test.exe`)
- [ ] Tool (`tool.exe`)
- [ ] Tool Fast (`tool_fast.exe` - unsupported)
- [ ] MegaloEdit (`MegaloEdit.exe`)
- [ ] In-game (MCC)

### Issue description

There's an extremely problematic issue with H2EK Sapien and Tagtest that makes certain missions virtually unworkable to add much to.

This crash occurs upon loading the second BSP on Metropolis, after adding a moderate amount of resources to various pallets (scenery, crates, vehicles, characters, etc). It has also happened on Outskirts, and my test Coagulation map for the same reasons - when a BSP is being loaded after a certain point putting resources in the pallets.

![image](https://github.com/Joint-Issue-Tracker/Joint-Issue-Tracker/assets/134641347/90256eb8-ed0d-44f1-867f-51f25638fc11)

This is what debug_full reports (relevant debug messages at the top and bottom)

![image](https://github.com/Joint-Issue-Tracker/Joint-Issue-Tracker/assets/134641347/1703ca0c-83be-46ae-945e-e0a43003603c)

It seems to be the debug memory is getting overloaded. This is probably why these BSP-loading crashes don't occur whatsoever when the map is compiled and played in MCC.

This is incredibly problematic and prevents working on and testing the mission - and it probably will affect many other missions than the ones I've tested so far, so finding a solution to this is very important.

### Reproduction steps

Can probably happen on many maps, but on Metropolis: add a moderate amount of resources to the character and vehicle pallets. Eventually, Tagtest or Sapien will crash upon trying to switch to BSP index #1. 

### Debug logs

![image](https://github.com/Joint-Issue-Tracker/Joint-Issue-Tracker/assets/134641347/90256eb8-ed0d-44f1-867f-51f25638fc11)

![image](https://github.com/Joint-Issue-Tracker/Joint-Issue-Tracker/assets/134641347/1703ca0c-83be-46ae-945e-e0a43003603c)

### How often does the issue occur?

100%

### Issue impact

This puts a very hard and uncharitable cap on what is possible in Halo 2 modding, depending on the scenario. This is very important to fix.

**Comment by RubyofBlue** [comment]
Further testing: I haven't been able to replicate this BSP-switching debug memory crash on any of Quarantine Zone's BSPs. I've added over 23 new entries to both the vehicle and character pallets, and still no crash. This makes me think earthcity_4 BSP (and outskirts bsp index # 0 to a lesser extent) is extremely poorly optimized and overloads the debug memory.

**Comment by RubyofBlue** [comment]
OK after stress testing the rest of the scenarios and their BSPs by throwing almost all the characters and vehicles into the pallets, here are the results:
Cairo: stable
Outskirts: BSP 0 prone to crash after switching to 1 or 2, then back to 0
Metropolis: BSP 1 extremely prone to crash
Arbiter: stable
Oracle: stable
Delta Halo: stable
Regret: stable
Scared Icon: BSP 1 prone to crash
Quarantine Zone: stable
Gravemind: stable
Uprising: stable
High Charity: stable
Great Journey: stable

**Comment by General-101** [comment]
Confirmed and repoed

**Comment by Crinon** [comment]
Also have this issue in Outskirts

**Comment by num0005** [comment]
looks like the table for tracking these allocations gets filled up, patching the executable to increase that table size might be a workaround, but can just downgrade the errors to warnings with the following patch (for sapien).

![image](https://github.com/Joint-Issue-Tracker/Joint-Issue-Tracker/assets/30047358/e1294865-efb3-4b69-886e-4fc011a5f237)

Would recommend just having less resources loaded at once.

**Comment by num0005** [comment]
![image](https://github.com/Joint-Issue-Tracker/Joint-Issue-Tracker/assets/30047358/937fe007-5529-40e0-b960-9887250b128b)
or for standalone

**Comment by Crinon** [comment]
> looks like the table for tracking these allocations gets filled up, patching the executable to increase that table size might be a workaround, but can just downgrade the errors to warnings with the following patch (for sapien).
> 
> ![image](https://private-user-images.githubusercontent.com/30047358/292686829-e1294865-efb3-4b69-886e-4fc011a5f237.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1ODg0NDIsIm5iZiI6MTcwMzU4ODE0MiwicGF0aCI6Ii8zMDA0NzM1OC8yOTI2ODY4MjktZTEyOTQ4NjUtZWZiMy00YjY5LTg4NmUtNGZjMDExYTVmMjM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDEwNTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5NTVjNGVmMjBjZTU1ZDFiMGNhY2ZlNmQyNjk0NGIxNDYwNjU1YjFhNjZmMGQ2MmMwZmVjNzJjMjM5NDMzZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D0ICSXBaDKq1XnOPILJMBrYdGrc4mHILAql7zvrjc9s)
> 
> Would recommend just having less resources loaded at once.

I confirm it fixes Sapien

**Comment by Crinon** [comment]
> ![image](https://private-user-images.githubusercontent.com/30047358/292687068-937fe007-5529-40e0-b960-9887250b128b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2Mjk0MDMsIm5iZiI6MTcwMzYyOTEwMywicGF0aCI6Ii8zMDA0NzM1OC8yOTI2ODcwNjgtOTM3ZmUwMDctNTUyOS00MGUwLWI5NjAtOTg4NzI1MGIxMjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDIyMTgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlZTRlMGU1OGU4ZTExOWQ1MzJlMTdiODE1ZTdkNGVlZTQ5YTU5YmJhOWY1MzJlNWMwY2ExNGQ3MWY2MWEyNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JC7rrhzDwND2JVRf8XWNYPXVm9LLRgEL4QXIku3Qwlo) or for standalone

Could you check you have the latest version of tagtest ? Hexa are not corresponding

**Comment by num0005** [comment]
> > ![image](https://private-user-images.githubusercontent.com/30047358/292687068-937fe007-5529-40e0-b960-9887250b128b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2Mjk0MDMsIm5iZiI6MTcwMzYyOTEwMywicGF0aCI6Ii8zMDA0NzM1OC8yOTI2ODcwNjgtOTM3ZmUwMDctNTUyOS00MGUwLWI5NjAtOTg4NzI1MGIxMjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDIyMTgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlZTRlMGU1OGU4ZTExOWQ1MzJlMTdiODE1ZTdkNGVlZTQ5YTU5YmJhOWY1MzJlNWMwY2ExNGQ3MWY2MWEyNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JC7rrhzDwND2JVRf8XWNYPXVm9LLRgEL4QXIku3Qwlo) or for standalone
> 
> Could you check you have the latest version of tagtest ? Hexa are not corresponding

Huh are you sure? I'm reasonably those addresses should work for the latest version of standalone.
